# Generated by Django 4.1.2 on 2023-02-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_userprofile_delete_contakt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('carrier', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date_shipped', models.DateField()),
                ('estimated_delivery', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
